/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/CHARACTER.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'animation_0'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Pelvis: THREE.Mesh
    LeftThigh: THREE.Mesh
    LeftShin: THREE.Mesh
    LeftFoot: THREE.Mesh
    LeftJoint_3: THREE.Mesh
    LeftJoint_1: THREE.Mesh
    LeftJoint: THREE.Mesh
    Right_Thigh: THREE.Mesh
    Right_Shin: THREE.Mesh
    Right_Foot: THREE.Mesh
    Right_Joint_3: THREE.Mesh
    Right_Joint_1: THREE.Mesh
    Right_Joint: THREE.Mesh
    ['Upper_Body-Mat3']: THREE.Mesh
    LeftUpper_Arm: THREE.Mesh
    LeftLower_Arm: THREE.Mesh
    LeftHand: THREE.Mesh
    LeftJoint_10: THREE.Mesh
    LeftJoint_4: THREE.Mesh
    LeftJoint_2: THREE.Mesh
    Right_Upper_Arm: THREE.Mesh
    Right_Lower_Arm: THREE.Mesh
    Right_Hand: THREE.Mesh
    Right_Joint_10: THREE.Mesh
    Right_Joint_4: THREE.Mesh
    Right_Joint_2: THREE.Mesh
    Head: THREE.Mesh
    Neck: THREE.Mesh
    ['Upper_Body-Mat1']: THREE.Mesh
    Joint: THREE.Mesh
  }
  materials: {
    ['Mat.1']: THREE.MeshStandardMaterial
    ['Mat.2']: THREE.MeshStandardMaterial
    ['Mat.3']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/CHARACTER.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="Null1" position={[-0.002, 0.406, 0]}>
          <group name="LeftFootGoal" position={[0.097, -0.348, 0.295]} rotation={[-0.447, 0.007, 0.004]}>
            <group name="Spherical_Field" />
            <group name="LeftThighPole" position={[-0.004, 0.426, 0.037]} rotation={[0.087, 0, 0]} />
          </group>
          <group name="Right_FootGoal" position={[-0.099, -0.222, -0.397]} rotation={[0.813, -0.006, 0.006]}>
            <group name="Spherical_Field_1" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0} />
          </group>
          <group name="Figure" position={[0.002, -0.406, -0.007]} rotation={[-0.001, 0, 0.001]}>
            <mesh name="Pelvis" geometry={nodes.Pelvis.geometry} material={materials['Mat.1']} position={[0.003, 0.839, -0.002]} rotation={[0.154, -0.09, 0.008]}>
              <mesh name="LeftThigh" geometry={nodes.LeftThigh.geometry} material={materials['Mat.1']} position={[0.077, -0.053, 0]} rotation={[-0.773, -0.014, 0.121]}>
                <mesh name="LeftShin" geometry={nodes.LeftShin.geometry} material={materials['Mat.1']} position={[0, -0.381, 0]} rotation={[0.427, -0.021, -0.123]}>
                  <mesh name="LeftFoot" geometry={nodes.LeftFoot.geometry} material={materials['Mat.1']} position={[0.004, -0.428, 0]} rotation={[-0.255, 0.069, 0.051]}>
                    <mesh name="LeftJoint_3" geometry={nodes.LeftJoint_3.geometry} material={materials['Mat.2']} />
                  </mesh>
                  <mesh name="LeftJoint_1" geometry={nodes.LeftJoint_1.geometry} material={materials['Mat.2']} />
                </mesh>
                <mesh name="LeftJoint" geometry={nodes.LeftJoint.geometry} material={materials['Mat.2']} />
              </mesh>
              <mesh name="Right_Thigh" geometry={nodes.Right_Thigh.geometry} material={materials['Mat.1']} position={[-0.077, -0.053, 0]} rotation={[-0.127, 0.366, -0.038]}>
                <mesh name="Right_Shin" geometry={nodes.Right_Shin.geometry} material={materials['Mat.1']} position={[0, -0.381, 0]} rotation={[0.967, 0.117, 0.238]}>
                  <mesh name="Right_Foot" geometry={nodes.Right_Foot.geometry} material={materials['Mat.1']} position={[-0.004, -0.428, 0]} rotation={[-0.222, -0.239, -0.028]}>
                    <mesh name="Right_Joint_3" geometry={nodes.Right_Joint_3.geometry} material={materials['Mat.2']} />
                  </mesh>
                  <mesh name="Right_Joint_1" geometry={nodes.Right_Joint_1.geometry} material={materials['Mat.2']} />
                </mesh>
                <mesh name="Right_Joint" geometry={nodes.Right_Joint.geometry} material={materials['Mat.2']} />
              </mesh>
              <group name="Upper_Body" position={[0, 0.227, 0]} rotation={[0, -0.106, 0]}>
                <mesh name="Upper_Body-Mat3" geometry={nodes['Upper_Body-Mat3'].geometry} material={materials['Mat.3']} position={[0, 0.227, 0]} rotation={[0, -0.106, 0]} />
                <mesh name="LeftUpper_Arm" geometry={nodes.LeftUpper_Arm.geometry} material={materials['Mat.1']} position={[0.145, 0.232, 0]} rotation={[-0.136, -0.519, -1.207]}>
                  <mesh name="LeftLower_Arm" geometry={nodes.LeftLower_Arm.geometry} material={materials['Mat.1']} position={[0.331, 0, 0]} rotation={[0, -0.728, 0]}>
                    <mesh name="LeftHand" geometry={nodes.LeftHand.geometry} material={materials['Mat.1']} position={[0.291, 0, 0]}>
                      <mesh name="LeftJoint_10" geometry={nodes.LeftJoint_10.geometry} material={materials['Mat.2']} />
                    </mesh>
                    <mesh name="LeftJoint_4" geometry={nodes.LeftJoint_4.geometry} material={materials['Mat.2']} />
                  </mesh>
                  <mesh name="LeftJoint_2" geometry={nodes.LeftJoint_2.geometry} material={materials['Mat.2']} />
                </mesh>
                <group name="LeftHandGoal" position={[0.219, -0.239, 0.332]} />
                <mesh name="Right_Upper_Arm" geometry={nodes.Right_Upper_Arm.geometry} material={materials['Mat.1']} position={[-0.145, 0.232, 0]} rotation={[0.889, 0.387, 1.244]}>
                  <mesh name="Right_Lower_Arm" geometry={nodes.Right_Lower_Arm.geometry} material={materials['Mat.1']} position={[-0.331, 0, 0]} rotation={[0, 0.775, 0]}>
                    <mesh name="Right_Hand" geometry={nodes.Right_Hand.geometry} material={materials['Mat.1']} position={[-0.291, 0, 0]}>
                      <mesh name="Right_Joint_10" geometry={nodes.Right_Joint_10.geometry} material={materials['Mat.2']} />
                    </mesh>
                    <mesh name="Right_Joint_4" geometry={nodes.Right_Joint_4.geometry} material={materials['Mat.2']} />
                  </mesh>
                  <mesh name="Right_Joint_2" geometry={nodes.Right_Joint_2.geometry} material={materials['Mat.2']} />
                </mesh>
                <group name="Right_HandGoal" position={[-0.229, -0.286, -0.236]} />
                <mesh name="Head" geometry={nodes.Head.geometry} material={materials['Mat.1']} position={[0, 0.373, 0]} rotation={[0.2, 0, 0]}>
                  <mesh name="Neck" geometry={nodes.Neck.geometry} material={materials['Mat.2']} />
                </mesh>
                <mesh name="Upper_Body-Mat1" geometry={nodes['Upper_Body-Mat1'].geometry} material={materials['Mat.1']} />
                <mesh name="Joint" geometry={nodes.Joint.geometry} material={materials['Mat.2']} position={[0, -0.012, 0.002]} />
              </group>
            </mesh>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/CHARACTER.glb')
